//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    public partial class employee
    {
        public string employee1 { get; set; }
        public string phone_number { get; set; }
        public string company { get; set; }
        public string country { get; set; }
        public string zip_code { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string id { get; set; }

      
    }
}
